### PR TITLE
Add incorrect annotation fix

### PR DESCRIPTION
**Pull request by cookiedragon234**
fix for https://github.com/S-B99/KAMI/issues/22

### CODE REVIEW

**Comment by S-B99** [comment]
Bruh I was going to do this myself after I tested what the broken module are

**Comment by S-B99** [comment]
Also for some reason toggle doesn't toggle the real Sprint

**Comment by S-B99** [comment]
Aight ty though I'll merge once I have a pc

**Comment by blockparole** [comment]
Never tried this but i guess it could be backported to 086-KAMI like [this](https://gist.github.com/bhumphrey/3764983):
`git checkout <branch>`
`git fetch <other-fork-alias>`
`git cherry-pick <commit-hash>`
`git push <your-fork-alias>`

**Comment by S-B99** [comment]
That's correct ye

**Pull request merged**
