### PR TITLE
removes default gui background

### PR DESCRIPTION
**Pull request by snowmii**
`package me.zeroeightsix.kami.module.modules.misc;

import me.zeroeightsix.kami.module.Module;

@Module.Info(name = "CleanGUI", category = Module.Category.MISC)
public class CleanGUI extends Module {
}`

### CODE REVIEW

**Comment by S-B99** [comment]
It's incorrect
Screenshot_20191217_082138

**Comment by snowmii** [comment]
hmmm
but it works for me

**Comment by cookiedragon234** [comment]
Its incorrect because he's using decompiled code from the best 2b2t client, backdoored client.

Annotations are not meant to be surrounded by curly braces, thats a mistake from the deobfuscator.

**Comment by cookiedragon234** [comment]
Also just saying its fine to use this code but please provide credit.

Here's how you should write it:
```Java
	@Inject(method = "drawWorldBackground(I)V", at = @At(value = "HEAD"), cancellable = true)
	private void drawWorldBackgroundWrapper(int tint, CallbackInfo ci)
	{
		RenderGuiBackground event = new RenderGuiBackground();
		MinecraftForge.EVENT_BUS.post(event);

		if(this.mc.world != null && event.getResult() == Event.Result.ALLOW)
		{
			ci.cancel();
			return;
		}
	}
```

**Comment by snowmii** [comment]
i don't really know why it works on my kami 
and yes you're right

**Comment by cookiedragon234** [comment]
Also @S-B99 you should be more careful with merging commits, especially from people who are new to coding. Stuff like this is obviously stolen, and can get your repository DMCA'd.

**Comment by S-B99** [comment]
yea i know, should have a branch for this

**Comment by S-B99** [comment]
tbh i need help moving to master, and accepting stuff at features-master and pulling

**Comment by d1gress** [comment]
<@563138570953687061> wdym isnt features-master the new master?

**Comment by S-B99** [comment]
its not supposed to be

youre supposed to have a master and a second branch to accept prs into

**Comment by cookiedragon234** [comment]
@S-B99 well if you want I can handle pull requests, with reviewing and merging etc

**Comment by cookiedragon234** [comment]
Just make sure people aren't pushing directly to master

**Comment by S-B99** [comment]
yea, this can be a pull branch i guess?

i have a master branch that's protected and i keep it updated so i guess this *is* the pull branch

**Comment by S-B99** [comment]
@cookiedragon234 what is your RenderGuiBackground event? I don't have one

**Comment by cookiedragon234** [comment]
We dont need a seperate branch, just get them to make pull requests to master and I can review them.

The event is a custom one.

**Comment by snowmii** [comment]
that doesn't make sence , the event is custom and i write it in wrong way ,and it works??

**Comment by cookiedragon234** [comment]
What?

**Comment by S-B99** [comment]
it doesn't work

**Comment by S-B99** [comment]
it's not custom either, it's just pasted from backdoored

**Comment by cookiedragon234** [comment]
Ofc it doesnt work, your using broken code and the code I posted uses a custom event. And it is a custom event.

**Comment by S-B99** [comment]
i know. i'm telling them, because they're saying it works, for some reason

**Comment by cookiedragon234** [comment]
🗿

**Comment by S-B99** [comment]
moyai moment

**Comment by bigbulletuwu123** [comment]
😹

**Pull request merged**
