### PR TITLE
Fix #296

### LINKED ISSUE #296: npe when joining servers
happens even with all modules off

Screenshot_20191217_211628

asflkasf fuckianf asfa kill me a;i

### PR DESCRIPTION
**Pull request by EmotionalLove**
try this @S-B99

### CODE REVIEW

**Comment by S-B99** [comment]
2 sec aaa

**Comment by EmotionalLove** [comment]
Screen Shot 2019-12-18 at 5 57 39 AM
smh this is why

**Comment by S-B99** [comment]
wut

oh ok
does this pr have it fixed? or did you find the solution after?

**Comment by EmotionalLove** [comment]
> wut
> 
> oh ok
> does this pr have it fixed? or did you find the solution after?

It's fixed now. It didn't have anything to do with the new ModuleManager code. It was someone spelled "FakeVanillaClient" wrong and only wrote "FakeVanilla"

**Comment by EmotionalLove** [comment]
Please merge

**Comment by S-B99** [comment]
ah alright. 15 sec building to test

**Comment by cookiedragon234** [comment]
This is why we reference classes by class not by name!!!!

**Comment by S-B99** [comment]
wasn't my decision to use names in the first place. see issue #295

**Pull request merged**
