### PR TITLE
warn instead of disabling autoqmain when not on 2b2t.org

### PR DESCRIPTION
**Pull request by Deauthorized**
warn instead of disabling the module entirely, change the formatting if you want#
#160

### CODE REVIEW

**Comment by Deauthorized** [comment]
> 
> 
> i made new chat stuff

epic

**Comment by Deauthorized** [comment]
just realized that since its hooked to update it may or may not spam the living fuck out of the users chat

**Comment by d1gress** [comment]
change it to onEnable or whatever the equivalent is

**Comment by S-B99** [comment]
No, make it run every 10 minutes instead. This will only show the user once, and as my other warning messages have shown people don't read those usually

**Comment by cookiedragon234** [comment]
This is a bad idea, what if the user is playing using a proxy like 2bored2wait, or if the user is on the test server (test.2b2t.org)? What is even the purpose of warning them anyway, I think that the best person to decide whether or not they're on 2b2t is the user themselves and not the client.

**Comment by S-B99** [comment]
Sure I guess. That makes more sense. They can just disable it it it interferes.

**Pull request merged**
