### PR TITLE
AutoTP

### PR DESCRIPTION
**Pull request by Katatje**
Automatically accepts/declines tpa requests.

### CODE REVIEW

**Comment by S-B99** [comment]
Why is this called AutoTP and not AutoTPA

**Comment by Katatje** [comment]
eeeh, idk

**Comment by S-B99** [comment]
rename pls i don't have descriptions working and autotp sounds stupid

**Comment by S-B99** [comment]
you only have to do the visible name class name doesn't matter that much

**Comment by Katatje** [comment]
ok

**Pull request merged**
