### PR TITLE
True Durability and Friends List

### PR DESCRIPTION
**Pull request by TheBritishMidget**

### CODE REVIEW

**Comment by TheBritishMidget** [comment]
here is the true durability

**Comment by S-B99** [comment]
Ayy you figured it out. Ty I'll look at it later uwu

**Comment by TheBritishMidget** [comment]
also there is friends list

**Comment by S-B99** [comment]
o I'd prefer different pull requests for different features but ty <3

**Comment by TheBritishMidget** [comment]
oh sorry XD

**Comment by S-B99** [comment]
Also for your imports, in the future, you can be more efficient by deleting the * line and then alt tabbing anything that errors in intellij. This avoids it importing literally everything in the package.

**Comment by TheBritishMidget** [comment]
kk XD

**Comment by TheBritishMidget** [comment]
IDK WHY IT KEEPS GOING TO HERE???

**Comment by d1gress** [comment]
make branches

**Comment by S-B99** [comment]
I know I just taught them how

**Comment by S-B99** [comment]
@TheBritishMidget aaa can you do that

**Pull request merged**
