### PR TITLE
Aliases!

### PR DESCRIPTION
**Pull request by Vonr**
very untested because everything broke

### CODE REVIEW

**Comment by S-B99** [comment]
> conflicting files
> 11

**Comment by Vonr** [comment]
fixing as im writing this, basically all my files are correct but github is dumb fuck

**Comment by S-B99** [comment]
It all says conflicting because your IDE changed the formatting / tab spaces whatever. Look at Command.java for example. It says you replaced the entire file, so github's diff can't tell if it actually conflicts or not.

**Comment by Vonr** [comment]
no, wait a second, this isnt even a good pr because its from a different kami blue ill unfork everything

**Comment by S-B99** [comment]
Yep, you're using 3 spaces per tab instead of 4. That's why

**Comment by S-B99** [comment]
Oh ok nvm lol

**Pull request closed without merging**
