### PR TITLE
Change AutoQMain to use ticks

### PR DESCRIPTION
**Pull request by d1gress**

### CODE REVIEW

**Comment by d1gress** [comment]
wait what it no work

**Comment by d1gress** [comment]
ok fixed

**Comment by d1gress** [comment]
<@563138570953687061>

**Comment by S-B99** [comment]
Why did that work

**Comment by d1gress** [comment]
<@563138570953687061> merge my pee ares

**Comment by cookiedragon234** [comment]
@everyone <@everyone>

**Comment by SpicyBigDaddy-alt** [comment]
<@563138570953687061>

**Comment by S-B99** [comment]
i was walking the dog

**Pull request merged**
